[build]
  # Build command with legacy peer deps
  command = "npm install --legacy-peer-deps && npm run build:client"

  # Output directory (where the built files are)
  publish = "dist/spa"

[functions]
  # Directory for serverless functions
  directory = "netlify/functions"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Build processing settings
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
